language: ruby

sudo: false

cache:
  apt: true
  bundler: true
  directories:
  - "$TRAVIS_BUILD_DIR/tmp/.htmlproofer"

notifications:
  email:
    on_success: never

branches:
  only: master

env:
  global:
  - JEKYLL_ENV=production
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # resolve SSL issue of htmlproofer
    - locales-all

rvm:
- 2.5
- 2.6

script:
- bundle exec jekyll build --trace

after_success:
# https://github.com/gjtorikian/html-proofer/wiki/Using-HTMLProofer-From-Ruby-and-Travis
- bundle exec htmlproofer ./_site
  --check-external-hash
  --check-opengraph
  --check-sri
  --check-html
  --http-status-ignore 999
  --check-img-http
  --timeframe 4w || true

after_script:
- find ./_site -type f

before_deploy:
- openssl aes-256-cbc -K $encrypted_18c079ac24d9_key -iv $encrypted_18c079ac24d9_iv -in tools/deploy_rsa.enc -out "$DEPLOY_SSH_KEY" -d
- eval "$(ssh-agent -s)"
- chmod 600 "$DEPLOY_SSH_KEY"
- ssh-add "$DEPLOY_SSH_KEY"

deploy:
- ls "$DEPLOY_SSH_KEY"

# vim: set tw=79 ts=2 sw=2 ai si et:
