url: "https://www.wgdd.de"
title: "[erfahrungen, meinungen, halluzinationen]"
email: webmaster@wgdd.de
description: >-
  Ein private Webseite mit Blog über Software, Fotografie, Aquaristik und
  alles, was mich sonst noch beschäftigt.
locale: "de"
github_username: dleidert
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.20.2
minimal_mistakes_skin: "default"
# Outputting
permalink: /:year/:month/:title/
paginate: 10 # amount of posts to show
paginate_path: /blog/page:num/
timezone: Europe/Berlin

include:
  - _pages
  - .htaccess

author:
  name: "Daniel Leidert"
  location: "Dresden, GER"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Chemiker, Programmierer, Debian-Entwickler, Hobby-Fotograf und tätig im Bereich Umweltschutz"
  email: "daniel@wgdd.de"
  github: "dleidert"
  instagram: "daniel.leidert"
#  uri: "https://www.wgdd.de"
  xing: "Daniel_Leidert"
  youtube: "https://www.youtube.com/channel/UCcByb2fCTx7B8QwZBdGxDgA"
#  links:
#    - label: "Paypal"
#      icon: "fab fa-fw fa-paypal"
#      url: "https://www.paypal.me/dleidert"
#      description: "Donate"

footer:
  links:
    - label: "Quellcode"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dleidert/www.wgdd.de"
    - label: "Kontakt"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:webmaster@wgdd.de"
    - label: "Patreon"
      icon: "fab fa-fw fa-patreon"
      url: "https://www.patreon.com/dleidert"
    - label: "Impressum"
      url: /impressum/
    - label: "Datenschutz"
      url: /datenschutz/

collections:
  debian:
    output: true
    permalink: /:collection/:path/
    order:
      - debian.md
      - packages.md
  fotografie:
    output: true
    permalink: /:collection/:path/
    order:
      - natur.md
      - portrait.md
      - makro.md
  aquaristik:
    output: true
    permalink: /:collection/:path/
    order:
      - danio/margaritatus.md
      - danio/erythromicron.md
  ueber:
    output: true
    permalink: /:path/
    order:
      - ueber.md
      - impressum.md
      - datenschutz.md

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _debian
  - scope:
      path: ""
      type: debian
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "debian"
  # _ueber
  - scope:
      path: ""
      type: ueber
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "ueber"
  # other collections
  - scope:
      path: ""
#      type: fotografie
    values:
      layout: single
      author_profile: true
#  - scope:
#      path: ""
#      type: aquaristik
#    values:
#      layout: single
#      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

feed:
  categories:
    - debian
    - planet-debian

plugins:
#  - jekyll-data
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jemoji

# vim: set tw=79 ts=2 sw=2 ai si et:
