title: "[erfahrungen, meinungen, halluzinationen]"
email: webmaster@wgdd.de
description: >-
  
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
locale: "de"
github_username: dleidert
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.17.2
minimal_mistakes_skin: "neon"
# Outputting
permalink: /:year/:month/:title/
paginate: 10 # amount of posts to show
paginate_path: /blog/page:num/
timezone: Europe/Berlin

include:
  - _pages

author:
  name   : "Daniel Leidert"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Chemiker, Programmierer, Debian-Entwickler, Hobby-Fotograf und tätig im Bereich Umweltschutz"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.wgdd.de"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dleidert"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/daniel.leidert"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dleidert"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/daniel.leidert"

collections:
  debian:
    output: true
    permalink: /:collection/:path/
    order:
      - debian.md
      - packages.md
    lang: "en"
  photography:
    output: true
    permalink: /:collection/:path/
    order:
      - nature.md
      - portrait.md
      - macro.md
  about:
    output: true
    permalink: /:path/
    order:
      - about.md
      - legal.md
      - privacy.md

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _debian
  - scope:
      path: ""
      type: debian
    values:
      layout: single
      author_profile: true
      lang: "en"
      sidebar:
        nav: "debian"
  # _about
  - scope:
      path: ""
      type: about
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "about"
  # other collections
  - scope:
      path: ""
      type: photography
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

feed:
  categories:
    - debian
    - planet-debian

plugins:
#  - jekyll-data
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jemoji

# vim: set tw=79 ts=2 sw=2 ai si et:
